### ISSUE TITLE
Directory Selection Window Launch

### ISSUE THREAD

**Issue by kulshresthaa** [wleepang/shiny-directory-input#1]
Hi, 
First of all, thank you for putting this together, very very helpful. I was struggling to find something so that user can select directory location for shiny App. Great job!

Question: I am running it on windows and when I click on the widget to browse the folder, the separate little R window does not pop up on the top of web browser (I am running the app in browser) and instead it is shown in the background and sometimes user may not notice this window after clicking the widget. Is there any minor change I can make at my end so that the window is always on top of the browser?

Thanks again for this great work. 

Ashish

**Comment by wleepang** [comment]
Hi Ashish,

On a Windows system it is using the `choose.dir()` function in the `utils` package that ships with R.  As far as I can tell there are no arguments to this function control the z-order / modality of the dialog that is displayed.

A possible solution would be to mask `choose.dir()` with a function that calls a Windows Scripting Host script via `system2()`.  Therein you would probably have more control with how the dialog is displayed.  This is similar to what is done for Mac OS X since `choose.dir()` is not available.

Lee
