### ISSUE TITLE
Minimum PowerShell version in windows

### ISSUE THREAD

**Issue by SiggiSmara** [wleepang/shiny-directory-input#19]
Just to let you know, and maybe we should put that in the readme somewhere but I leave that up to you to decide.

I ran into a problem using the new dialog script on a freshly installed windows 7. Although it has PowerShell installed, the version is 2 and for the script to work you need version 3 or higher it seems.

It is simple to install (can be downloaded from Microsoft for free) and once it is installed the script works fine. On windows 8 and beyond the default is to install at least 3 or higher so I think this is only an issue for windows 7.

**Comment by kmshort** [comment]
This completely fails on Windows 10, v.1909. 

`Processing -File 'C:\Program' failed because the file does not have a '.ps1' extension. Specify a valid Windows PowerShell script file name, and then try again.,Windows PowerShell,Copyright (C) Microsoft Corporation. All rights reserved.,,Try the new cross-platform PowerShell https://aka.ms/pscore6,`

**Comment by wleepang** [comment]
Updated README with Powershell requirements in 137dc696785de10e9a402aecca09ab191a822ce2
